name = "GeoSurrogates"
uuid = "7068cc40-2035-44e5-a3a1-4a05757b754b"
version = "1.0.0-DEV"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
ImageFeatures = "92ff4b2b-8094-53d3-b29d-97f740f06cef"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Landfire = "16f38fd6-0379-4569-89bb-2d3d56e50de8"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RasterDataSources = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ADTypes = "1.20.0"
ArchGDAL = "0.10.10"
BlockArrays = "1.9.3"
CategoricalArrays = "1.0.2"
DataFrames = "1.8.1"
DimensionalData = "0.29.25"
Distances = "0.10.12"
Extents = "0.1.6"
GeoFormatTypes = "0.4.5"
GeoInterface = "1.6.0"
GeometryBasics = "0.5.10"
GeometryOps = "0.1.31"
ImageFeatures = "0.5.3"
ImageFiltering = "0.7.12"
ImageTransformations = "0.10.2"
Images = "0.26.2"
Interpolations = "0.16.2"
Landfire = "0.0.1"
LazyArrays = "2.9.4"
Lux = "1.27.1"
Optimisers = "0.4.6"
ProgressMeter = "1.11.0"
Random = "1.11.0"
RasterDataSources = "0.7.2"
Rasters = "0.14.7"
Statistics = "1.11.1"
StatsAPI = "1.8.0"
StatsBase = "0.34.9"
StatsModels = "0.7.7"
StyledStrings = "1.11.0"
Tables = "1.12.1"
julia = "1.6.7"

[extras]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
RasterDataSources = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

[targets]
test = ["Test", "p7zip_jll", "Zygote"]
