name = "GeoSurrogates"
uuid = "7068cc40-2035-44e5-a3a1-4a05757b754b"
version = "1.0.0-DEV"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
ImageFeatures = "92ff4b2b-8094-53d3-b29d-97f740f06cef"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
Distances = "0.10.12"
Extents = "0.1.6"
GeoFormatTypes = "0.4.5"
GeoInterface = "1.6.0"
GeometryBasics = "0.5.10"
GeometryOps = "0.1.31"
ImageFeatures = "0.5.3"
ImageFiltering = "0.7.12"
ImageTransformations = "0.10.2"
Images = "0.26.2"
Interpolations = "0.16.2"
Rasters = "0.14.7"
StatsModels = "0.7.7"
julia = "1.6.7"

[extras]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
RasterDataSources = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
