[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoSurrogates = "7068cc40-2035-44e5-a3a1-4a05757b754b"
RapidRefreshData = "6311d174-80ed-4991-8be9-d0557cea290a"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tyler = "e170d443-b9d6-418a-9ee8-061e966341ef"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
