project:
  type: book
  output-dir: _site

engine: julia
julia:
  project: "."

execute:
  freeze: auto
  timeout: 600

book:
  title: "GeoSurrogates.jl"
  search:
    location: sidebar
    keyboard-shortcut:
      - "/"
  navbar:
    right:
      - icon: star
        href: https://github.com/RallypointOne/GeoSurrogates.jl/stargazers
        text: "Star"
      - icon: github
        href: https://github.com/RallypointOne/GeoSurrogates.jl
  chapters:
    - part: "Docs"
      chapters:
        - index.qmd
        - getting-started.qmd
        - examples.qmd
    - part: "API"
      chapters:
        - api.qmd
    - part: "Reference"
      chapters:
        - changelog.qmd
        - coverage.qmd

  page-footer:
    center: "Built on __BUILD_DATE__"

language:
  search-text-placeholder: "Search  (/)"

format:
  html:
    css: styles.css
    number-sections: false
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    include-after-body:
      - file: _version-selector.html
